name: uv python test

on: [push, pull_request]

jobs:
  builds:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5
        
      - name: setting python
        uses: actions/setup-python@v5
        with:
            python-version-file: ".python-version"

      - name: install depedencies
        run: |
          uv add torch
          uv add pytest

      - name: testing
        run: uv run pytest --verbose
